### ISSUE TITLE
Are capital letters preserved?

### ISSUE THREAD

**Issue by Ginden** [charlesLoder/greek-transliteration#2]
I have string `Α108` ([Greek Capital Letter Alpha](https://unicode-table.com/en/0391/)). Online version translates it as `a108` (small letter).

**Comment by charlesLoder** [comment]
@Ginden 

SBL's handbook was a little ambiguous in regards to capitals. Note in the snapshot below that both alphas are transliterated with a lowercase 'a' and this is the case for every character.

![image](https://user-images.githubusercontent.com/32489748/127028457-a0757203-46ca-4a66-ab3c-509d2f69d37e.png)

But the capital pi below is transliterated with an uppercase 'P'

![image](https://user-images.githubusercontent.com/32489748/127028653-97708529-f8d7-4da1-9388-b230dc9f9960.png)

I went with the former since the latter was implicit.

---

An option like:

```js
transliterate("Αλφα", { capitals: true })
// Alpha
```

would not be difficult to implement
